import { z } from 'zod';

export const createReportSchema = z.object({
  body: z.object({
    reportType: z.enum([
      'monthly_summary',
      'quarterly_export',
      'annual_statistics',
      'quality_report',
      'payment_report',
      'custom',
    ]),
    periodStart: z.string().datetime('Invalid period start date format').or(z.date()),
    periodEnd: z.string().datetime('Invalid period end date format').or(z.date()),
    generatedBy: z.string().min(1, 'Generated by user ID is required'),
    data: z.record(z.unknown(), {
      errorMap: () => ({ message: 'Data must be a valid JSON object' }),
    }),
    status: z.enum(['draft', 'submitted', 'approved', 'rejected']).default('draft').optional(),
  }),
});

export const updateReportSchema = z.object({
  body: z.object({
    reportType: z.enum([
      'monthly_summary',
      'quarterly_export',
      'annual_statistics',
      'quality_report',
      'payment_report',
      'custom',
    ]).optional(),
    periodStart: z.string().datetime('Invalid period start date format').optional().or(z.date()),
    periodEnd: z.string().datetime('Invalid period end date format').optional().or(z.date()),
    data: z.record(z.unknown()).optional(),
    status: z.enum(['draft', 'submitted', 'approved', 'rejected']).optional(),
  }),
  params: z.object({
    id: z.string().min(1, 'Report ID is required'),
  }),
});

export const getReportSchema = z.object({
  params: z.object({
    id: z.string().min(1, 'Report ID is required'),
  }),
});

export const deleteReportSchema = z.object({
  params: z.object({
    id: z.string().min(1, 'Report ID is required'),
  }),
});

export const submitReportSchema = z.object({
  params: z.object({
    id: z.string().min(1, 'Report ID is required'),
  }),
});

export const approveReportSchema = z.object({
  params: z.object({
    id: z.string().min(1, 'Report ID is required'),
  }),
});

export const rejectReportSchema = z.object({
  params: z.object({
    id: z.string().min(1, 'Report ID is required'),
  }),
});

export const listReportsSchema = z.object({
  query: z.object({
    reportType: z.enum([
      'monthly_summary',
      'quarterly_export',
      'annual_statistics',
      'quality_report',
      'payment_report',
      'custom',
    ]).optional(),
    status: z.enum(['draft', 'submitted', 'approved', 'rejected']).optional(),
    generatedBy: z.string().optional(),
    page: z.string().optional(),
    limit: z.string().optional(),
  }),
});

