'use client';

import Link from 'next/link';
import { CreateReportDialog } from '@/components/admin/CreateReportDialog';
import { FileText, Loader2, Plus } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useReports } from '@/hooks/useReports';
import { format } from 'date-fns';

export default function ReportsPage() {
    const { data: reports, isLoading } = useReports();

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">NAEB Reports</h1>
                    <p className="text-muted-foreground">
                        Generate and view reports
                    </p>
                </div>
                <CreateReportDialog />
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Reports</CardTitle>
                    <CardDescription>
                        View and manage NAEB reports
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    {isLoading ? (
                        <div className="flex justify-center py-8">
                            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                        </div>
                    ) : !reports || reports.length === 0 ? (
                        <div className="text-center py-12">
                            <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4 opacity-50" />
                            <h3 className="text-lg font-medium mb-2">No reports found</h3>
                            <p className="text-muted-foreground mb-4">Generate your first report to get started</p>
                            <CreateReportDialog
                                trigger={
                                    <Button className="gap-2">
                                        <Plus className="h-4 w-4" />
                                        Generate Report
                                    </Button>
                                }
                            />
                        </div>
                    ) : (
                        <div className="space-y-4">
                            {reports.map((report: any) => (
                                <div key={report.id} className="p-4 border rounded-lg hover:bg-accent/50 transition-colors">
                                    <div className="flex items-center justify-between">
                                        <div>
                                            <p className="font-medium capitalize">{report.reportType.replace(/_/g, ' ')}</p>
                                            <p className="text-sm text-muted-foreground">
                                                {report.periodStart && report.periodEnd
                                                    ? `${format(new Date(report.periodStart), "MMM d, yyyy")} - ${format(new Date(report.periodEnd), "MMM d, yyyy")}`
                                                    : 'N/A'}
                                            </p>
                                            <p className="text-xs text-muted-foreground mt-1">Generated by {report.generatedByUser?.name || 'Unknown'}</p>
                                        </div>
                                        <div className="flex gap-3 items-center">
                                            <span className={`px-2 py-1 text-xs rounded-full font-medium ${report.status === 'approved' ? 'bg-green-500/15 text-green-700 dark:text-green-400' :
                                                report.status === 'rejected' ? 'bg-red-500/15 text-red-700 dark:text-red-400' :
                                                    report.status === 'submitted' ? 'bg-blue-500/15 text-blue-700 dark:text-blue-400' :
                                                        'bg-yellow-500/15 text-yellow-700 dark:text-yellow-400'
                                                }`}>
                                                {report.status}
                                            </span>
                                            <Button size="sm" variant="ghost" asChild>
                                                <Link href={`/admin/reports/${report.id}`}>
                                                    View
                                                </Link>
                                            </Button>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    );
}

